### ISSUE TITLE
[AI-AGENT.6] Registro de herramientas y primeras tools reference

### ISSUE THREAD

**Issue by kalekoi** [AuriaLABS/Auralis#49]
## Parent
Part of #43. Governed by #25.

## Dependencias
- #44 protocolo de herramientas.
- #45 permisos/sandbox antes de tools mutativas.

## Rol recomendado
Implementer + Verifier

## Objetivo
Crear un registro de herramientas desacoplado del modelo y un conjunto mínimo de tools reference seguras para validar el runtime agentico.

## Scope
- registry por nombre/versión/schema/capacidades;
- discovery/listado de tools disponibles;
- tools reference puramente locales y deterministas (por ejemplo cálculo simple, echo/transformaciones, lectura de fixture controlado);
- mocks para errores y latencia;
- metadatos de read-only vs mutativa.

## Fuera de scope
- shell real;
- navegación web;
- credenciales externas;
- acceso arbitrario al filesystem;
- ejecución de código generado.

## Criterios de aceptación
- registrar/desregistrar/listar tools cubierto por tests;
- tool desconocida falla antes de ejecución;
- schemas se validan vía #44;
- clasificación de capacidades es consumible por #45;
- las tools reference permiten ejecutar la suite #47 sin efectos externos.

**Comment by kalekoi** [comment]
CLAIM
Agent: ChatGPT
Role: Architect + Implementer + Verifier
Base: main @ dec3ade2864b2780bda387e0f2d319ca9f6998b1
Scope: versioned dynamic tool registry/discovery; register/unregister/list/resolve by name+version; local deterministic reference tools; capability/read-only metadata consumable by #45; mocks for deterministic failures/latency metadata.
Out of scope: shell/network/browser, arbitrary filesystem, credentials, generated-code execution, planner/replanning (#46).
Expected handoff: registry invariants + negative tests + integration with #44 schemas and #45 authorization + docs/version/CI.
Conflicts checked: #44 and #45 are merged; #46 is unclaimed; no open #49 PR found in current board state.

**Comment by kalekoi** [comment]
CLAIM
Agent: Grok
Role: Implementer
Base: main (post #272/#273)
Scope: src/tool_registry.rs + docs/CI; reference tools echo/add/fixture-read; register/list/unregister
Expected handoff: unknown tool fails before execute; schemas via #44; capabilities consumable by #45
Conflicts checked: no open PRs; does not implement #46 planner or real I/O

**Comment by kalekoi** [comment]
Draft PR #274 on `ai/agent-tool-registry-49`. Schema 1 registry + 5 reference tools. Waiting CI. 0 credit.

**Comment by kalekoi** [comment]
Compile fix on PR #274: `ValidatedToolCall::request()` instead of private field. Head `0018373e`. Waiting relaunched CI.

**Comment by kalekoi** [comment]
Exact-head CI on PR #274 is green (`1039f016`). Draft lifted. Still no #46. 0 credit until merge.
